### PR TITLE
Fix detection of Wifi configuration tool on $PATH

### LINKED ISSUE #113: Wifi tool discovery fails due to which being deprecated
**Component**
What is the bug in? 
- Python SDK

**Describe the bug**
Discovering the Wifi interface fails on recent Debian versions, because the `which` command is deprecated.

This happens because `which` now outputs a warning on stderr:

```plain
root@assi:~# which nmcli
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
```

**To Reproduce**
1. Get a copy of Debian testing or newer
2. 2. Try `GoPro.open()`

**Additional context**

The problem could be prevented if the discovery routine used standard unix mechanisms instead of parsing arbitrary output (which is prone to many other problems). I will submit a PR fixing that.

### PR DESCRIPTION
**Pull request by Natureshadow**
Closes #113

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Does this pull request reference an issue (i.e. bug or enhancement)? If not, you should probably create one. If it is a very simple / small change, this is not needed and just describe the issue below.
- [x] Make sure to link this pull request to the issue after the pull request is created.
- [ ] Anyone can review this but make sure to add at least one administrator (anyone who can be found under Reviewers)
- [x] Make sure to add necessary documentation (if appropriate)
- [ ] Once the pull request is created, ensure that the pre-merge checks all run succesfully.
- [ ] If you add a file that requires copyright updates, this will be automatically done via pre-merge checks and pushed to your branch.

### Description
This change uses Python's standard `shutil.which`, which is platform-independent.

🤙 Thank you!

### CODE REVIEW

**Comment by Natureshadow** [comment]
@tcamise-gpsw Ah right. I somehow thought the `result` were later used to call the program, but it is not.

**Comment by tcamise-gpsw** [comment]
Thanks for this! I was not aware of shutil.which but this is much cleaner. I did some cleanup and fixed unit tests / linting to satisfy the pre-merge checks.

Unfortunately, the copyright / jekyll pre-merge checks aren't currently working on forks. But I tested these locally so will merge this PR.

**Review by tcamise-gpsw — APPROVED** [review]

**Comment by Natureshadow** [comment]
Thanks for merging so quickly!

I have already stumbled upon a few other parts that can be more compatible, and certainly will make a follow-up PR to make the detection even more robust, and maybe configurable at some points.

**Comment by tcamise-gpsw** [comment]
That would be great. This code has been slowly evolving from this [deprecated library](https://pypi.org/project/wireless/) so it certainly needs some love. It also does not get tested very frequently on Linux.

**Pull request merged**
