### PR TITLE
Demo/ionic

### PR DESCRIPTION
**Pull request by sultanmyrza**
### Add GoPro Demo project (ionic framework + capacitor 3)

**Works for both iOS and Android**
✅ . Connect phone to GoPro via bluetooth
✅ . Send Bluetooth Commands (take photo, get wifi creds, shut down)
✅ .  Connect phone to GoPro via WiFi
✅ .  Download files to phone from GoPro via WiFi

@tcamise-gpsw [here is the quick demo for ios and android 
](https://github.com/sultanmyrza/OpenGoPro/tree/demo/ionic/demos/ionic#you-can-also-preview-video-demos-for)

🤙 Thank you!

### CODE REVIEW

**Comment by sultanmyrza** [comment]
@tcheema-gpsw what have no idea what `Pre Merge Checks / copyright (pull_request) ` it means?

**Comment by tcamise-gpsw** [comment]
Yeah something is wrong with the pre-merge checks. I'm looking into it now.

**Comment by tcamise-gpsw** [comment]
You probably don't care about this but it turns out I'm running into https://github.com/actions/checkout/issues/455 when accepting pull requests from forks. I worked around it by updating the copyrights on your forked repo.

**Review by tcamise-gpsw — APPROVED** [review]
Awesome work here!!! 👏 

I have very little experience in any part of this stack but was able to get this working out of the box 👍 

FYI I moved it into a new directory (demos/ionic/file_transfer) for consistency with the rest of the demos.

**Pull request merged**
