### PR TITLE
Add endpoint for deleting media files

### PR DESCRIPTION
**Pull request by KonradIT**
Noticed the endpoint has been added to GoPro HERO10 Black v1.30 firmware and GoPro Hero9 Black v1.70 firmwares. Tested it and it works great!

### CODE REVIEW

**Comment by KonradIT** [comment]
@tcamise-gpsw any way this endpoint can be documented officially?

**Comment by tcamise-gpsw** [comment]
I haven't forgot about this, there's just a lot going on here:

1. I need to double check but I don't think there is a good reason why we haven't documented this. If that is the case, then yes it needs to be added to the specs.

2. However, these *.md files are autogenerated from an internal repo so we can't take PR's on them. I can leave this PR open for the Python SDK change.

3. I'm realizing now that the github actions infrastructure in this repo is not designed to handle PR's from forked repos. This is a problem and something that I need to look into.

**Comment by KonradIT** [comment]
No worries. I've been using the endpoint for my own uses and its good.

**Comment by tcamise-gpsw** [comment]
This is being tracked via internal ticket so closing this PR

**Comment by Fougl** [comment]
Hi, Is this working now? @KonradIT can you please help: how can I delete it with python?

**Pull request closed without merging**
