### PR TITLE
Update wifi controller and add argument to run without wifi

### PR DESCRIPTION
**Pull request by tcamise-gpsw**
Add enum for WiFi Controller SSID state.
Add detection of wifi enabled / disabled in Windows
Add default argument to connect to GoPro without enabling Wifi.
Added example to poll battery

### CODE REVIEW

**Comment by lonndoggie** [comment]
Hi Tim, this looks...well...interesting to say the least.

**Review by lonndoggie — COMMENTED** [review]
Testing external user revew/comment ability

**Review by lonndoggie — APPROVED** [review]
On second thought, sure, this LGTM.

**Review by KonradIT — APPROVED** [review]
Works!

Untitled

**Pull request merged**
